### ISSUE TITLE
Inconsistent types in `kore_x` family of functions

### ISSUE THREAD

**Issue by sskeirik** [runtimeverification/pyk#453]
This is fairly minor, but I wanted to share it.

In `kore/prelude.py`, we have:

-   `kore_{set|list|map}` take Python native types (containing Kore wrappers) and return Kore wrappers.

In `kore/match.py`, we have:

-   `kore_{int|bool|str|bytes}` take Kore wrappers and return Python native types, with the inverse provided by the function `dv`.

Ideally:

-   one family of functions goes from Python native types to wrapped Kore types;
-   one family of functions goes from wrapped Kore types to Python native types.

**Comment by tothtamas28** [comment]
I agree, this asymmetry is indeed confusing. Let's fix it.

So these are the current names:

|          | prelude.py                    | match.py                                  |
|----------|-------------------------------|-------------------------------------------|
| `Bool`   | `bool_dv(bool) -> DV`         | `kore_bool(P) -> bool`                    |
| `Int`    | `int_dv(int) -> DV`           | `kore_int(P) -> int`                      |
| `String` | `string_dv(str) -> DV`        | `kore_str(P) -> str`                      |
| `Bytes`  | `bytes_dv(bytes) -> DV`       | `kore_bytes(P) -> bytes`                  |
| `List`   | `kore_list(*P) -> P`          | `match_list(P) -> tuple[P, ...]`          |
| `Set`    | `kore_set(*P) -> P`           | `match_set(P) -> tuple[P, ...]`           |
| `Map`    | `kore_map(*tuple[P, P]) -> P` | `match_map(P) -> tuple[tuple[P, P], ...]` |


There are also higher-order functions

| K Sort |  match.py                                                |
|--------|----------------------------------------------------------|
| `List` | `kore_list_of(P -> T) -> (P -> tuple[T, ...])`           |
| `Set`  | `kore_set_of(P -> T) -> (P -> tuple[T, ...])`            |
| `Map`  | `kore_map_of(P -> K, P -> V) -> tuple[tuple[K, V], ...]` |

I guess the reason for `kore_int` (instead of the more symmetric `match_int`) is to play well with these combinators:

```python3
kore_list_of(kore_int)(pattern)  # extracts list[int]
```

---

Notation:

* `P` abbreviates `Pattern`
* `T` is a type variable
* `*P` denotes `*args: P`
* `X -> Y` denotes `Callable[[X], Y]`

**Comment by tothtamas28** [comment]
`string_dv` should be renamed to `str_dv`. It's shorter, and then it could also be read as "`str` to `DV`". This also works with the `match.py` counterpart: `kore_str` is "KORE (`Pattern`) to `str`".

Along these same lines, how about we rename `kore_list` to `list_pattern`? It's a bit longer unfortunately, but it resolves the asymmetry issue, while still enables the easy-to-read `kore_list_of(kore_int)`?

Like this:

|          | prelude.py              | match.py                         |
|----------|-------------------------|----------------------------------|
| `String` | `str_dv(str) -> DV`     | `kore_str(P) -> str`             |
| `List`   | `list_pattern(*P) -> P` | `match_list(P) -> tuple[P, ...]` |

@sskeirik, what do you think?

**Comment by sskeirik** [comment]
I think the suggestion sounds good. I think a similar renaming of `kore_set` and `kore_map` to `set_pattern` and `map_pattern` for consistency would also be good.

**Comment by tothtamas28** [comment]
> a similar renaming of `kore_set` and `kore_map` to `set_pattern` and `map_pattern` for consistency would also be good

Definitely.
