### ISSUE TITLE
Can not make sense of the `ValueError(f'Claim labels not found: {unfound_labels}')`

### ISSUE THREAD

**Issue by yanliu18** [runtimeverification/pyk#868]
KMIR attemps to add a feature allowing proving a single claim. There is a ValueError of an initial implemantention based on `KProve.get_claims`. The error message is as follows. The error msg does not make sense to me.
```
ValueError: Claim labels not found: ['SIMPLE-SPEC.S', 'SIMPLE-SPEC.I', 'SIMPLE-SPEC.M', 'SIMPLE-SPEC.P', 'SIMPLE-SPEC.L', 'SIMPLE-SPEC.E', 'SIMPLE-SPEC.-', 'SIMPLE-SPEC.S', 'SIMPLE-SPEC.P', 'SIMPLE-SPEC.E', 'SIMPLE-SPEC.C', 'SIMPLE-SPEC..', 'SIMPLE-SPEC.s', 'SIMPLE-SPEC.t', 'SIMPLE-SPEC.a', 'SIMPLE-SPEC.t', 'SIMPLE-SPEC.e', 'SIMPLE-SPEC.m', 'SIMPLE-SPEC.e', 'SIMPLE-SPEC.n', 'SIMPLE-SPEC.t', 'SIMPLE-SPEC..', 'SIMPLE-SPEC.1']
```

# Steps to reproduce:
From master branch, main directory
```bash
git checkout feature/prove-a-claim
cd kmir
make build
source set_env.sh
poetry shell
kmir prove ../demo/simple-spec.k --claim SIMPLE-SPEC.statement.1
```
where `SIMPLE-SPEC.statement.1` should be a claim label in `simple-spec.k`.

The error result shoud be generated from 

# Expected:
`kmir prove ../demo/simple-spec.k --claim SIMPLE-SPEC.statement.1` should prove the specified claim.

Or what should be use as input to select a claim to prove?

PR #https://github.com/runtimeverification/mir-semantics/pull/325 depends on this issue.

**Comment by ehildenb** [comment]
@yanliu18 it's best to:

- APL (Always Post Links): link to `simple-spec.k` directly.
- Minimize examples. Best to make a minimal test that the team upstream can use as an example to work with directly rather than 
- Attach each issue to a project board (in this case, the K board).

Thanks for the issue report!

**Comment by ehildenb** [comment]
It appears to me that the issues is that you're passing `--claim SIMPLE-SPEC.statement.1`. Because of the way that KMIR CLI is made in https://github.com/runtimeverification/mir-semantics/pull/325, it is interpreting the single claim name as a list of claim names (which is what upstream pyk expects).

So if we adjust that PR to follow the same convention of using a list of claims like `--claim CLAIM1 --claim CLAIM2` (by using the upstream pyk CLI options), then this issue should go away.

**Comment by yanliu18** [comment]
> It appears to me that the issues is that you're passing `--claim SIMPLE-SPEC.statement.1`. Because of the way that KMIR CLI is made in [runtimeverification/mir-semantics#325](https://github.com/runtimeverification/mir-semantics/pull/325), it is interpreting the single claim name as a list of claim names, one for each character in the supplied claim name. This is because upstream pyk expects a list of claim names, not a single name.
> 
> So if we adjust that PR to follow the same convention of using a list of claims like `--claim CLAIM1 --claim CLAIM2` (by using the upstream pyk CLI options), then this issue should go away.

The call to pyk was implemented here: https://github.com/runtimeverification/mir-semantics/blob/d5ceab8380276098548c9a2a206e33367868c97e/kmir/src/kmir/kmir.py#L115
The single was converted to a interable before sent to pyk.

But your message helped find the cause. The conversion was mistakenly done and the error message was confusing when `SIMPLE-SPEC` was there.

The issue is gone now. Thanks.
