### ISSUE TITLE
Store node attributes directly on the node

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/pyk#965]
Separated from https://github.com/runtimeverification/pyk/issues/919

Currently in the KCFG, we store the list of attributes as separate from the nodes themselves. Instead, we can make a `NodeAtt` class and store the list of attributes directly as a field on the node. This makes it easy to have a uniform attribute system that works even as we add more attributes, and to allow users to register hooks for checking different node attributes on loading new nodes.

For example, this issue (https://github.com/runtimeverification/pyk/issues/964), we have that on loading a proof we are checking each node for being terminal. But we could also just rely on the fact that every node, when entered into the graph, is checked for all the attributes the user may care about, and so we know that nodes which are `terminal` are already marked as such. No need to have explicit place in algorithm to mark them as such, and no need to check them on load time.

**Comment by ehildenb** [comment]
Another issue that came up, @PetarMax is working on minimizing KCFGs for summarization, and found that node attributes are sticking around post-summarization when they probably shouldn't (in this one) https://github.com/runtimeverification/pyk/pull/995

Attaching attributes directly to nodes would solve this issue too.

Any updates @nwatson22 ?

**Comment by nwatson22** [comment]
I've been thinking about this some, and I wasn't sure how we can eliminate the need to check on load time, since `KCFG.from_dict` loads components of the graph one at a time, but the attributes themselves may depend on other parts of the graph. Would it be a good idea to only check when the node is first added to the graph except `from_dict`, and then have all the attributes be saved/loaded from disk, the way `vacuous` and `stuck` already are?
